services:

  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - scp_network
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "123456"]
    environment:
      - REDIS_USER=yourusername  # Redis社区版
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123456", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3  
      start_period: 5s

  rabbitmq:
    image: rabbitmq:management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=louwenjie
    networks:
      - scp_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  scp_network:
    driver: bridge
    name: scp_network

volumes:
  logs:
    name: scp_logs
  redis_data:
    name: scp_redis_data
  rabbitmq_data:
    name: scp_rabbitmq_data